# Default values for coco-diamond.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
image:
  repository: coco/coco-diamond-auto
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 512Mi
env:
  INTERVAL: 60
  PREFIX: coco.servers

